language: none

services:

build:
  pre_ci:
  pre_ci_boot:
    image_name: sireum/ci
    image_tag: latest
    pull: true
    options: "-e HOME=/root"
  ci:
    - >
      if [[ ! `git show -s HEAD | grep -F -q "[skip shippable]"` ]]; then
        export COURSIER_CACHE=$SHIPPABLE_BUILD_DIR/cache/coursier &&
        git submodule update --init --recursive &&
        bin/build.cmd test &&
        bin/sireum;
      fi
  post_ci:
  on_success:
  on_failure:
  push:
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/bin/linux/java
    - $SHIPPABLE_BUILD_DIR/bin/linux/z3
    - $SHIPPABLE_BUILD_DIR/bin/scala
    - $SHIPPABLE_BUILD_DIR/cache/coursier
