FROM ubuntu:18.04
MAINTAINER Robby <robby@k-state.edu>
RUN apt update && \
    apt install -y wget && \
    apt upgrade -y && \
    apt install -y git zip unzip libgomp1 xz-utils build-essential automake cmake aspcud curl python \
                   locales bc libc6-dev libgmp-dev libsodium-dev nano software-properties-common zlib1g-dev gcc \
                   g++ nodejs && \
    add-apt-repository universe && \
    add-apt-repository ppa:avsm/ppa && \
    apt update && \
    apt install -y p7zip-full m4 opam && \
    locale-gen en_US en_US.UTF-8 && \
    dpkg-reconfigure locales && \
    rm -rf /var/lib/apt/lists/* && \
    opam init -vv --debug --comp=4.06.1 --disable-sandboxing --reinit -a -j 4 && \
    eval `opam env` && \
    opam install coq=8.9.0 -vv --debug -y -j 4
