FROM sireum/ci:latest
MAINTAINER Robby <robby@k-state.edu>
RUN apt update && \
    apt upgrade -y && \
    eval `opam env` && \
    opam install menhir=20181113 -vv --debug -y -j 4 && \
    git clone --recursive -b v3.5 https://github.com/AbsInt/CompCert.git && \
    cd CompCert && \
    ./configure x86_64-linux && \
    make -j 4 all && \
    make install && \
    rm -fR CompCert
