#!/bin/bash
read -p "Enter the directory where Sireum should be installed under [Press Enter for ~/Applications]: " INSTALL_PATH
INSTALL_PATH=${INSTALL_PATH:-~/Applications}
mv Sireum ${INSTALL_PATH}/
rm -- "$0"