# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  required_plugins = %w( vagrant-vbguest )
  _retry = false
  required_plugins.each do |plugin|
    unless Vagrant.has_plugin? plugin
      system "vagrant plugin install #{plugin}"
      _retry=true
    end
  end

  if (_retry)
    exec "vagrant " + ARGV.join(' ')
  end

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider :virtualbox do |vb|
    vb.cpus = 4
    vb.memory = 16384
    vb.gui = true
    vb.linked_clone = false
    vb.customize ["modifyvm", :id, "--vram", "64"]
    vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  if ENV['FIRST_RUN'] == 'true'
    config.vbguest.auto_update = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    adduser vagrant vboxsf
    apt-get install -y unzip cmake nodejs aspcud m4 zsh \
                       python3-pip python3-sphinx python3-pygments python3-wheel \
                       apt-transport-https gnupg-agent xubuntu-desktop
    # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    # add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    # sudo apt-get update
    # sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    apt-get autoremove -y
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    export PATH=$PATH:$HOME/.local/bin
    pip3 install pygments-style-github sphinx_bootstrap_theme
    sudo sed s/required/sufficient/g -i /etc/pam.d/chsh
    chsh -s /bin/zsh
    sudo sed s/sufficient/required/g -i /etc/pam.d/chsh
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    echo 'export SIREUM_HOME=$HOME/Sireum' >> "$HOME/.zshrc"
    echo 'export JAVA_HOME=$SIREUM_HOME/bin/linux/java' >> "$HOME/.zshrc"
    echo 'export SCALA_HOME=$SIREUM_HOME/bin/scala' >> "$HOME/.zshrc"
    echo 'export Z3_HOME=$SIREUM_HOME/bin/linux/z3' >> "$HOME/.zshrc"
    echo 'export PATH=$SIREUM_HOME/bin:$SIREUM_HOME/linux/bin:$JAVA_HOME/bin:$SCALA_HOME/bin:$Z3_HOME/bin:$PATH' >> "$HOME/.zshrc"
    git clone --recursive https://github.com/sireum/kekinian Sireum
    cd Sireum
    bin/build.cmd native || exit -1
    bin/install/compcert.cmd || exit -1
    bin/install/clion.cmd || exit -1
    bin/install/fmide.cmd || exit -1
    bin/build.cmd setup || exit -1
  SHELL

end
