name: macOS-CompCert

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:

  ci:
    runs-on: macOS-latest
    steps:
      - name: Clean
        run: |
          rm -fR "$GITHUB_WORKSPACE/Sireum"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Sireum
          submodules: recursive
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v4
        with:
          path: Sireum/bin/mac/java
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-compcert-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v4
        with:
          path: Sireum/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-compcert-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v4
        with:
          path: Sireum/cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('Sireum/versions.properties') }}-compcert-coursier
      - name: Cache CompCert
        id: cache-compcert
        uses: actions/cache@v4
        with:
          path: |
            Sireum/bin/mac/.compcert.ver
            Sireum/bin/mac/.coq.ver
            Sireum/bin/mac/.menhir.ver
            Sireum/bin/mac/.opam.ver
            Sireum/bin/mac/.opam
            Sireum/bin/mac/opam
          key: ${{ runner.os }}-${{ hashFiles('Sireum/bin/install/opam.cmd','Sireum/bin/install/compcert.cmd') }}-compcert
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/Sireum/cache/coursier
          cd $GITHUB_WORKSPACE/Sireum
          .ci/macOS-compcert.sh
